import { useState } from "react";

interface Session {
  id: number;
  title: string;
  preview: string;
  time: string;
  messages: Message[];
}

interface Message {
  role: "bot" | "user" | "proposal";
  text: string;
  dataBlock?: string;
  proposalLabel?: string;
  proposalActions?: boolean;
  tools?: string[];
}

const sessions: Session[] = [
  {
    id: 1,
    title: "ROAS Drop Analysis",
    preview: "Analyzing spend and frequency...",
    time: "Today 14:32",
    messages: [
      { role: "bot", text: "Olá. Tenho acesso aos dados de Velaris Co. / Orbit. O que você quer analisar?" },
      { role: "user", text: "O ROAS caiu essa semana. O que está acontecendo?" },
      {
        role: "bot",
        text: 'Analisando os últimos 7 dias…\n\nCriativo saturado. Quer proposta de redistribuição de budget?',
        dataBlock: 'Spend: R$12.400 (+18% WoW)\nLeads: 89 (-22% WoW)\nCPL: R$139 (+52% WoW) ⚠\n"Orbit v3" → freq 4.8, CTR -31% WoW\n72% da queda concentrada nesta campanha',
        tools: ["get_campaign_metrics", "get_account_targets"],
      },
      { role: "user", text: "Sim. Qual o impacto esperado?" },
      {
        role: "proposal",
        proposalLabel: "⚡ PROPOSAL — AWAITING APPROVAL",
        text: "1. Pausar 'Orbit v3' → libera R$340/dia\n2. Lookalike 1%: R$400 → R$740/dia (+85%)\nImpacto estimado: ROAS 4.2× → 4.9×, CPL R$89 → R$72 (-19%)",
        proposalActions: true,
        tools: ["pause_ad", "adjust_budget"],
      },
    ],
  },
  {
    id: 2,
    title: "Creative Brief — Lookalike",
    preview: "Generating brief for new angle...",
    time: "Yesterday 09:18",
    messages: [
      { role: "bot", text: "Olá. Sessão de brief de criativo para Lookalike 1%. Quer que eu analise os comentários dos anúncios atuais para identificar os ângulos mais eficazes?" },
      { role: "user", text: "Sim" },
      {
        role: "bot",
        text: "Análise de sentimento dos comentários concluída.\n\nAngulos mais eficazes:\n• Social proof com dados numéricos (CTR 4.2% vs média 2.8%)\n• Depoimentos curtos em vídeo (< 15s)\n• CTA com benefício direto\n\nBrief gerado:\n\n**Hook:** \"Empresas como a sua crescem 4× mais rápido\"\n**Angle:** Dado real de performance — ROAS 5.1× comprovado\n**Objections addressed:** \"Sem tempo para gerenciar\" / \"Já tentei ferramentas assim\"\n**CTA:** \"Comece seu trial grátis →\"\n**Format:** Vídeo vertical 9:16, até 12 segundos\n**Reference comment:** \"Dobrei meu ROAS em 3 semanas\" — @maria_growth\n**Rationale:** Comentários com social proof numérico geram 2.3× mais engajamento",
        tools: ["analyze_creative_sentiment", "generate_creative_brief"],
      },
      { role: "user", text: "Gera uma imagem para o ad." },
      {
        role: "bot",
        text: "Imagem gerada com base no brief:\n\n[Image generated by Ideogram API · Awaiting your approval before publishing]",
        tools: ["generate_image"],
      },
    ],
  },
  {
    id: 3,
    title: "Week 10 Summary",
    preview: "Weekly performance digest...",
    time: "Mar 12 08:00",
    messages: [
      { role: "bot", text: "Olá. Tenho acesso aos dados de Velaris Co. / Orbit. O que você quer analisar?" },
      { role: "user", text: "Me dá o resumo da semana 10." },
      {
        role: "bot",
        text: "Resumo Semana 10 — Orbit:\n\n✅ ROAS total: 4.2× (acima da meta)\n⚠ Frequência subiu para 4.1 no ad set principal\n✅ CPL caiu 12% vs semana anterior\n⚠ CTR do \"Orbit v3\" em queda há 4 dias\n\nRecomendações:\n1. Diversificar criativos do ad set principal\n2. Aumentar budget do Lookalike 1%\n3. Considerar pausa do \"Orbit v3\" se tendência continuar",
        tools: ["get_campaign_metrics", "get_account_targets"],
      },
    ],
  },
];

const availableTools = [
  "get_campaign_metrics", "get_account_targets", "analyze_creative_sentiment",
  "generate_creative_brief", "generate_image", "pause_ad", "adjust_budget",
  "create_ad", "get_competitor_intel", "get_utm_health",
];

const AIAgent = () => {
  const [activeSession, setActiveSession] = useState(0);
  const [sessionStates, setSessionStates] = useState<Record<number, { executed?: boolean; messages: Message[] }>>(
    Object.fromEntries(sessions.map((s, i) => [i, { messages: [...s.messages] }]))
  );
  const [input, setInput] = useState("");
  const [typing, setTyping] = useState(false);

  const currentMessages = sessionStates[activeSession]?.messages || [];

  const handleExecute = () => {
    setSessionStates(prev => ({
      ...prev,
      [activeSession]: {
        ...prev[activeSession],
        executed: true,
        messages: prev[activeSession].messages.map(m =>
          m.role === "proposal" ? { ...m, proposalActions: false } : m
        ),
      },
    }));
  };

  const handleNewConversation = () => {
    const newId = Object.keys(sessionStates).length;
    setSessionStates(prev => ({
      ...prev,
      [newId]: {
        messages: [{ role: "bot", text: "Olá. Tenho acesso aos dados de Velaris Co. / Orbit. O que você quer analisar?" }],
      },
    }));
    setActiveSession(newId);
  };

  const handleSend = () => {
    if (!input.trim() || typing) return;
    const text = input.trim();
    setInput("");
    setSessionStates(prev => ({
      ...prev,
      [activeSession]: {
        ...prev[activeSession],
        messages: [...prev[activeSession].messages, { role: "user", text }],
      },
    }));
    setTyping(true);
    setTimeout(() => {
      setSessionStates(prev => ({
        ...prev,
        [activeSession]: {
          ...prev[activeSession],
          messages: [
            ...prev[activeSession].messages,
            { role: "bot", text: "Analisando seus dados... Identifico que a principal oportunidade agora é otimizar o budget allocation entre os ad sets ativos. Quer que eu elabore uma proposta?", tools: ["get_campaign_metrics"] },
          ],
        },
      }));
      setTyping(false);
    }, 1500);
  };

  return (
    <div className="p-10 dash-page-enter flex flex-col" style={{ height: "calc(100vh - 44px - 40px)" }}>
      <h1 className="text-[30px] font-bold tracking-[-0.04em] text-dash-text-primary mb-1">AI Agent</h1>
      <p className="text-[14px] text-dash-text-secondary mb-6">Chat with your data. Analyze, propose, execute — all in one conversation.</p>

      <div className="flex-1 flex border border-dash-border rounded-lg overflow-hidden min-h-0">
        {/* Sessions panel */}
        <div className="w-[220px] bg-dash-sidebar border-r border-dash-border flex flex-col">
          <div className="px-3 pt-3 pb-2">
            <div className="text-[10px] font-semibold uppercase tracking-[0.07em] text-dash-text-tertiary">Conversations</div>
          </div>
          <div className="flex-1 overflow-auto">
            {sessions.map((s, i) => (
              <button
                key={s.id}
                onClick={() => setActiveSession(i)}
                className={`w-full text-left px-3 py-2.5 transition-colors ${
                  activeSession === i ? "bg-dash-active" : "hover:bg-dash-hover"
                }`}
              >
                <div className="text-[13px] font-medium text-dash-text-primary truncate">{s.title}</div>
                <div className="text-[11px] text-dash-text-tertiary truncate">{s.preview}</div>
                <div className="text-[10px] text-dash-text-tertiary mt-0.5">{s.time}</div>
              </button>
            ))}
          </div>
          <div className="p-2 border-t border-dash-border space-y-1">
            <button
              onClick={handleNewConversation}
              className="w-full text-[12px] text-dash-text-secondary border border-dash-border rounded-md hover:text-dash-text-primary hover:bg-dash-hover py-2 transition-colors"
            >
              + New conversation
            </button>
            <button className="w-full text-[11px] text-dash-text-tertiary hover:text-dash-text-secondary py-1 rounded-md transition-colors">
              ↑ Import from meeting
            </button>
          </div>
        </div>

        {/* Chat pane */}
        <div className="flex-1 flex flex-col min-h-0">
          <div className="flex-1 overflow-auto p-5 flex flex-col gap-3">
            {currentMessages.map((msg, i) => {
              if (msg.role === "user") {
                return (
                  <div key={i} className="self-end max-w-[85%] bg-dash-text-primary text-white rounded-lg px-3.5 py-2.5 text-[13px] leading-relaxed">
                    {msg.text}
                  </div>
                );
              }
              if (msg.role === "proposal") {
                const executed = sessionStates[activeSession]?.executed;
                if (executed) {
                  return (
                    <div key={i} className="self-start max-w-[90%] bg-dash-green-bg border border-[hsl(155,40%,85%)] rounded-lg px-4 py-3 text-[13px] text-dash-green">
                      ✓ Actions sent for execution via Meta API. Confirmation in ~2 min.
                    </div>
                  );
                }
                return (
                  <div key={i} className="self-start max-w-[90%]">
                    <div className="bg-dash-lime-bg border-l-[3px] border-dash-lime rounded-lg px-4 py-3">
                      <div className="text-[10px] font-bold uppercase tracking-[0.07em] text-dash-lime mb-2">{msg.proposalLabel}</div>
                      <div className="text-[13px] text-dash-text-primary whitespace-pre-line leading-relaxed mb-3">{msg.text}</div>
                      {msg.proposalActions && (
                        <div className="flex gap-2">
                          <button onClick={handleExecute} className="text-[12px] font-medium bg-dash-text-primary text-white px-3.5 py-1.5 rounded-md">✓ Execute</button>
                          <button className="text-[12px] text-dash-text-secondary border border-dash-border px-3.5 py-1.5 rounded-md">Dismiss</button>
                          <button className="text-[12px] text-dash-text-tertiary px-3.5 py-1.5">View details</button>
                        </div>
                      )}
                    </div>
                    {msg.tools && (
                      <div className="flex gap-1 mt-1.5 flex-wrap">
                        {msg.tools.map(t => (
                          <span key={t} className="text-[9px] font-medium px-1.5 py-0.5 rounded bg-dash-active text-dash-text-tertiary">{t}</span>
                        ))}
                      </div>
                    )}
                  </div>
                );
              }
              // bot
              return (
                <div key={i} className="self-start max-w-[88%]">
                  <div className="bg-dash-sidebar border border-dash-border rounded-lg px-3.5 py-2.5 text-[13px] text-dash-text-primary leading-relaxed">
                    {msg.dataBlock && (
                      <>
                        <span>{msg.text.split("\n\n")[0]}</span>
                        <div className="mt-2 bg-background border border-dash-border rounded px-3 py-2 font-mono text-[11.5px] text-dash-text-secondary leading-relaxed whitespace-pre-line">
                          {msg.dataBlock}
                        </div>
                        <div className="mt-2">{msg.text.split("\n\n").slice(1).join("\n\n")}</div>
                      </>
                    )}
                    {!msg.dataBlock && <span className="whitespace-pre-line">{msg.text}</span>}
                  </div>
                  {msg.tools && (
                    <div className="flex gap-1 mt-1.5 flex-wrap">
                      {msg.tools.map(t => (
                        <span key={t} className="text-[9px] font-medium px-1.5 py-0.5 rounded bg-dash-active text-dash-text-tertiary">{t}</span>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
            {typing && (
              <div className="self-start bg-dash-sidebar border border-dash-border rounded-lg px-4 py-3 flex gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-dash-text-tertiary typing-dot" />
                <span className="w-1.5 h-1.5 rounded-full bg-dash-text-tertiary typing-dot" />
                <span className="w-1.5 h-1.5 rounded-full bg-dash-text-tertiary typing-dot" />
              </div>
            )}
          </div>

          {/* Tool chips */}
          <div className="px-3 pt-2 flex flex-wrap gap-1">
            {availableTools.map(t => (
              <span key={t} className="text-[9px] font-medium px-1.5 py-0.5 rounded border border-dash-border text-dash-text-tertiary">{t}</span>
            ))}
          </div>

          {/* Input */}
          <div className="border-t border-dash-border p-3 flex gap-2 items-center">
            <input
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={e => e.key === "Enter" && handleSend()}
              placeholder="Ask, analyze, or propose…"
              className="flex-1 bg-dash-sidebar border border-dash-border rounded-md px-3 py-2 text-[13px] text-dash-text-primary placeholder:text-dash-text-tertiary outline-none focus:border-dash-text-secondary transition-colors"
            />
            <button
              onClick={handleSend}
              className="w-8 h-8 bg-dash-text-primary text-white rounded-md flex items-center justify-center text-[13px] hover:opacity-90 transition-opacity"
            >
              ↑
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIAgent;
